### ISSUE TITLE
Deploy rstudio docker image on VICE

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#147]
final steps required from #80 to get image analysis vignette running in rstudio.

* need to make sure rstudio docker image supports python / terrautils
* should automagically update on dockerhub
* ask tyson to make sure updated image is available in VICE

**Comment by Chris-Schnaufer** [comment]
Tyson agrees to work with Kimberly on this

**Comment by kimberlyh66** [comment]
@dlebauer or @Chris-Schnaufer Tyson wants to know what version of R to use to build the VICE base image. 

Should this version be determined based off of what version of R the (terraref rstudio docker container)[https://github.com/terraref/toolserver-dockerfiles/blob/master/rstudio/Dockerfile] is built from?

**Comment by kimberlyh66** [comment]
@dlebauer or @Chris-Schnaufer Tyson wants to know what version of R to use to build the VICE base image. 

Should this version be determined based off of what version of R the [terraref rstudio docker container](https://github.com/terraref/toolserver-dockerfiles/blob/master/rstudio/Dockerfile) is built from?

**Comment by dlebauer** [comment]
Yes, it should be based off the terraref one that is based off rocker/geospatial

________________________________

**Comment by dlebauer** [comment]
@tyson-swetnam please advise on status of VICE deployment and let @kimberlyh66  know if she can help or deploy this app.

**Comment by tyson-swetnam** [comment]
I have pushed a base RStudio Geospatial 3.4.2 to DockerHub, 

https://hub.docker.com/r/cyversevice/rstudio-geospatial/tags 

when I try to build the Terra Ref RStudio image, it throws several errors (incompatible packages) and dies on `plantcv`, e.g.

```
ERROR: influxdb 5.2.2 has requirement python-dateutil>=2.6.0, but you'll have python-dateutil 2.5.3 which is incompatible.
ERROR: cfunits 3.0.0 has requirement numpy>=1.15, but you'll have numpy 1.12.1 which is incompatible.
ERROR: jsonschema 3.0.1 has requirement six>=1.11.0, but you'll have six 1.10.0 which is incompatible.
ERROR: pyclowder 2.2.0 has requirement requests==2.21.0, but you'll have requests 2.22.0 which is incompatible.
```
```
* installing *source* package ‘traits’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘crul’ 0.4.0 is being loaded, but >= 0.6.0 is required
ERROR: lazy loading failed for package ‘traits’
* removing ‘/usr/local/lib/R/site-library/traits’
Installation failed: Command failed (1)
```

```

Installed /usr/local/lib/python2.7/dist-packages/plantcv-3.4.1+61.ge5f5b91-py2.7.egg
Processing dependencies for plantcv==3.4.1+61.ge5f5b91
Searching for plotnine
Reading https://pypi.python.org/simple/plotnine/
Downloading https://files.pythonhosted.org/packages/8f/77/20761215737d9eeb0342cdf96fe4474dd353fc83825828b23d8aecaa7748/plotnine-0.5.1.tar.gz#sha256=4d1ac43ccc061719a9ca549ba2df4877a2ea62ba9865878e4cb12547fea112bb
Best match: plotnine 0.5.1
Processing plotnine-0.5.1.tar.gz
Writing /tmp/easy_install-p4XzcY/plotnine-0.5.1/setup.cfg
Running plotnine-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-p4XzcY/plotnine-0.5.1/egg-dist-tmp-i1KT3k
  File "build/bdist.linux-x86_64/egg/plotnine/stats/stat.py", line 12
    class stat(metaclass=Registry):
                        ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/scales/scale.py", line 22
    class scale(metaclass=Registry):
                         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/ggplot.py", line 847
    raise TypeError(msg) from err
                            ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/utils.py", line 776
    class Registry(type, metaclass=RegistryMeta):
                                  ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/guides/guide.py", line 5
    class guide(metaclass=Registry):
                         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/coords/coord_cartesian.py", line 74
    **train(scale_x, self.limits.xlim, 'x'),
                                           ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/coords/coord_trans.py", line 94
    **train(scale_x, self.limits.xlim, self.trans.x, 'x'),
                                                         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/geoms/geom.py", line 12
    class geom(metaclass=Registry):
                        ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/themes/themeable.py", line 20
    class themeable(metaclass=RegistryHierarchyMeta):
                             ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/plotnine/positions/position.py", line 11
    class position(metaclass=Registry):
                            ^
SyntaxError: invalid syntax

UPDATING build/lib.linux-x86_64-2.7/plotnine/_version.py
set build/lib.linux-x86_64-2.7/plotnine/_version.py to '0.5.1'
creating /usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg
Extracting plotnine-0.5.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/ggplot.py", line 847
    raise TypeError(msg) from err
                            ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/utils.py", line 776
    class Registry(type, metaclass=RegistryMeta):
                                  ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/stats/stat.py", line 12
    class stat(metaclass=Registry):
                        ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/scales/scale.py", line 22
    class scale(metaclass=Registry):
                         ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/guides/guide.py", line 5
    class guide(metaclass=Registry):
                         ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/coords/coord_cartesian.py", line 74
    **train(scale_x, self.limits.xlim, 'x'),
                                           ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/coords/coord_trans.py", line 94
    **train(scale_x, self.limits.xlim, self.trans.x, 'x'),
                                                         ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/geoms/geom.py", line 12
    class geom(metaclass=Registry):
                        ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/themes/themeable.py", line 20
    class themeable(metaclass=RegistryHierarchyMeta):
                             ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg/plotnine/positions/position.py", line 11
    class position(metaclass=Registry):
                            ^
SyntaxError: invalid syntax

Adding plotnine 0.5.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/plotnine-0.5.1-py2.7.egg
Searching for opencv-python<4,>=3.4
Reading https://pypi.python.org/simple/opencv-python/
No local packages or working download links found for opencv-python<4,>=3.4
error: Could not find suitable distribution for Requirement.parse('opencv-python<4,>=3.4')
The command '/bin/sh -c pip install -U six opencv-python && cd / &&  git clone https://github.com/danforthcenter/plantcv.git &&       cd /plantcv && python setup.py install' returned a non-zero code: 1
```

**Comment by dlebauer** [comment]
next steps 

1. [ ] get the https://github.com/terraref/toolserver-dockerfiles/blob/master/rstudio/3.4.2/Dockerfile to build
2. [ ] ask Tyson to copy-paste content from functioning dockerfile to a terraref vice instance 
3. [ ] learn to integrate new vice app and test
4. [ ] make the app public
5. [ ] Create a new issue to deploy a mirror of the terraref betydb somewhere that the vice images can read

**Comment by Chris-Schnaufer** [comment]
Change to epic and make new tickets
