### ISSUE TITLE
Create tutorials and templates for Done Pipeline

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#160]
Create Jupyter Notebook and videos on how to:
- [ ] Create an account on Clowder instance
- [ ] Upload drone data to the dataset
- [ ] Submit jobs for various processes
- [ ] Create and use extractors
- [ ] Create custom extractor chains

**Comment by Chris-Schnaufer** [comment]
Closing as no longer relevent
